wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1675485086.044732
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 23
      4: 3.9.13
      5: 0.13.5
      8:
      - 5
action_history_size:
  desc: null
  value: 3
action_smoothing:
  desc: null
  value: true
action_step_scaling:
  desc: null
  value: 20
alpha:
  desc: null
  value: 0.0003
apply_environment_seed:
  desc: null
  value: true
batch_size:
  desc: null
  value: 4096
beta:
  desc: null
  value: 0.0003
delta_T:
  desc: null
  value: 1
entropy_factor:
  desc: null
  value: 0.5
entropy_factor_final:
  desc: null
  value: 0.5
gamma:
  desc: null
  value: 0.999
input_dims:
  desc: null
  value: 26
maxsize_ReplayMemory:
  desc: null
  value: 100000
num_episodes:
  desc: null
  value: 100
num_episodes_pretrain:
  desc: null
  value: 100
num_obstacles:
  desc: null
  value: 5
object_size:
  desc: null
  value: 20
obstacle_step_scaling:
  desc: null
  value: 5
plot_durations:
  desc: null
  value: true
plot_sigma:
  desc: null
  value: true
pretrain:
  desc: null
  value: true
render_fps:
  desc: null
  value: 24
scheduler_period:
  desc: null
  value: 2
seed_init_value:
  desc: null
  value: 3407
select_action_filter:
  desc: null
  value: true
select_action_filter_after_episode:
  desc: null
  value: 70
sigma_final:
  desc: null
  value: 2.0
sigma_init:
  desc: null
  value: 2.0
sort_obstacles:
  desc: null
  value: true
target_update:
  desc: null
  value: 10
tau:
  desc: null
  value: 0.005
window_size:
  desc: null
  value: 512
